# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CalendarPlan' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CalendarPlan
pod 'Aspects','~>1.4.1'
pod 'Masonry','~>1.1.0'
pod 'PNChart','~>0.8.9'
pod 'MJRefresh','~>3.1.15.3'
pod 'MJExtension','~>3.0.15.1'
pod 'AFNetworking','~>3.2.1'
pod 'FMDB','~>2.7.2'
pod 'FSCalendar','~>2.7.9'




  target 'CalendarPlanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CalendarPlanUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
